# Generated by Django 5.1.5 on 2025-05-04 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_thumbnai'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='thumbnai',
            new_name='thumbnail',
        ),
    ]
